name: suma console workflows
run-name: ${{ github.actor}} is starting Github actions

on: 
  push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: test
    steps: 
      - run: echo "suma console"
      - uses: actions/checkout@v4
      - run: ls